
server:
    port: 8081

spring:
    datasource:
      url: jdbc:mysql://localhost:3307/shiro_learn
      username: root
      password: root
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5

    redis:
        database: 2
        host: 10.168.99.149
        port: 6379
        pool:
            max-active: 50
            max-idle: 8
            max-wait: 10000
            min-idle: 0
        timeout: 200